configs:
  migrations:
    file: ../
services:
  postgres:
    container_name: postgres
    image: postgres:16.3-alpine3.20
    pull_policy: missing
    labels:
      com.vnworkday.docker.name: postgres
      com.vnworkday.docker.project: vnworkday
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: dba
      POSTGRES_PASSWORD: ${DBA_PASSWORD}
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - type: bind
        source: ./conf/postgresql.conf
        target: /var/config/postgresql.conf
    command:
      - "postgres"
      - "-c"
      - "config_file=/var/config/postgresql.conf"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "dba" ]
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 3
  flyway:
    container_name: flyway
    build:
      context: ../
      dockerfile: ci/Dockerfile
    pull_policy: missing
    labels:
      com.vnworkday.docker.name: flyway
      com.vnworkday.docker.project: vnworkday
    restart: always
    configs:
      - migrations
    entrypoint: /bin/bash
    stdin_open: true
    stop_signal: SIGKILL
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "dba", "-h", "postgres" ]
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 3
    environment:
      DBA_PASSWORD: ${DBA_PASSWORD}
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:8.8
    pull_policy: missing
    labels:
      com.vnworkday.docker.name: pgadmin
      com.vnworkday.docker.project: vnworkday
    ports:
      - "5050:80"
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-dba@vnworkday.com}
      PGADMIN_DEFAULT_PASSWORD: ${DBA_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "wget", "-O", "-", "http://localhost:80/misc/ping" ]
      interval: 5s
      timeout: 5s
      start_period: 10s
      retries: 3
  wait:
    container_name: wait
    image: dokku/wait:latest
    pull_policy: missing
    labels:
      com.vnworkday.docker.name: wait
      com.vnworkday.docker.project: vnworkday
    restart: no
    depends_on:
      postgres:
        condition: service_healthy
      flyway:
        condition: service_healthy
      pgadmin:
        condition: service_healthy
networks:
  default:
    name: vnworkday
    external: true