[flyway]
locations = ["filesystem:./migrations/account/sql"]
failOnMissingLocations = true
baselineOnMigrate = true

[environments.local]
url = "jdbc:postgresql://postgres:5432/account?timezone=Asia/Ho_Chi_Minh"
user = "dba_account"