name: pull-request
run-name: Pull Request Lint by ${{ github.actor }}
on:
  # Trigger the workflow on pull request to main, staging, and production branches
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # TODO: Do anything make sense
  